version: '3'
services:

#-------------------------#
  
  wazigate-edge:
    container_name: wazigate-edge
    image: waziup/wazigate-edge:latest
    build: ./wazigate-edge
    ports:
      - "80:80"
      - "1883:1883"
    volumes:
      - ./wazigate-edge:/root/conf
      - ./apps:/root/apps # Where the WaziApps are installed
      - /var/run:/var/run # Mapping the host sockets
      - ./wazigate-edge:/go/src/github.com/Waziup/wazigate-edge # need it for development
      #- ./setup/resolv.conf:/etc/resolv.conf
    environment:
      - WAZIUP_HTTP_ADDR=:80
#      - WAZIUP_HTTPS_ADDR=:4443
#      - WAZIUP_MQTT_ADDR=:1883
#      - WAZIUP_MQTTS_ADDR=:8883
#      - WAZIUP_TLS_CRT =             TLS Cert File (.crt)
#      - WAZIUP_TLS_KEY =             TLS Key File (.key)
      - WAZIUP_MONGO=wazigate-mongo:27017
      - WAZIUP_CLOUDS_FILE=/root/conf/clouds.json
      #- WAZIGATE_HOST_ADDR=/var/run/wazigate-host.sock
    #network_mode: host
    depends_on:
      - wazigate-mongo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: curl --fail http://localhost/ || exit 1 
      interval: 30s
      retries: 10 # Will try for 5 minutes
    restart: always
    #entrypoint: tail -f /dev/null
    # entrypoint: "./wazigate-edge -www /go/src/github.com/Waziup/wazigate-edge/wazigate-dashboard" #used in dev mode

#-------------------------#

  wazigate-mongo:
    container_name: wazigate-mongo
    #image: waziup/wazigate-mongo:V1.1-Beta1
    image: webhippie/mongodb:latest
    #build: ./wazigate-mongo
    #hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./wazigate-mongo/data:/var/lib/mongodb
      - ./wazigate-mongo/backup:/var/lib/backup
      - ./wazigate-mongo/bin:/var/lib/bin
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/local --quiet
      interval: 5s
      timeout: 5s
      retries: 12
#    extra_hosts:
#      - "localhost:127.0.0.1"
#    network_mode: host
    restart: always
    #entrypoint: "/etc/init.d/mongodb stop; rm -f /var/lib/mongodb/mongod.lock; mongod --repair --dbpath=/var/lib/mongodb/ && mongod --dbpath=$
    #entrypoint: "tail -f /dev/null"
    entrypoint: "sh /var/lib/bin/start.sh"

#-------------------------#

networks:
  default:
    external:
      name: wazigate
