version: '3'
services:

  wazigate-mongo:
    container_name: "waziup.wazigate-mongo"
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/local --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    extra_hosts:
      - "localhost:127.0.0.1"
    network_mode: host                 # has to be fixed later to be accessed only locally
    restart: always
    entrypoint: "mongod --journal"

#-------------------------#